export async function seed(knex) {
  // First, delete all existing records in the "reviews" table
  await knex('reviews').del()

  // Now, insert 15 sample data entries into the "reviews" table with IDs
  await knex('reviews').insert([
    {
      id: 1,
      location: 'Café Belle',
      title: 'A Relaxing Meal at Café Belle',
      text: "I had a pawsitively delightful time at Café Belle. The staff was so friendly and welcoming to me. They even brought a water bowl, and I enjoyed sitting on the outdoor patio with my human. The smells were heavenly, and I couldn't resist begging for a bite of their delicious brunch. It's definitely one of my favorite spots!",
      rating: 5,
      date: '2023-10-30',
    },
    {
      id: 2,
      location: 'Ristorante Italiano',
      title: 'An Italian Adventure at Ristorante Italiano',
      text: "I woofingly approve of Ristorante Italiano! The outdoor patio is a dog's dream come true. I had a taste of their pasta, and it was 'pawsome.' The staff was so kind and even brought me some treats. Dining here with my human was a tail-wagging experience.",
      rating: 4,
      date: '2023-10-29',
    },
    {
      id: 3,
      location: 'Bistro de Paris',
      title: 'French Flavors and Canine Charm',
      text: 'I had a lovely evening at Bistro de Paris. The outdoor seating area was perfect for me. I got to watch the world go by while my human enjoyed escargot. The ambiance was cozy, and the smells were intriguing. A delightful spot for us pups!',
      rating: 4,
      date: '2023-10-28',
    },
    {
      id: 4,
      location: 'Harbor View Seafood',
      title: 'Seafood and Sunshine at Harbor View Seafood',
      text: 'Harbor View Seafood was a real catch for both me and my human. The sea breeze and view from the pet-friendly deck were amazing. I got to try a bit of their crab cake, and it was tail-waggingly good! A perfect place for seafood-loving pups.',
      rating: 5,
      date: '2023-10-27',
    },
    {
      id: 5,
      location: 'Café Magnolia',
      title: 'Coffee and Conversation at Café Magnolia',
      text: "Café Magnolia is a spot where I always feel at home. The staff is so friendly and accommodating to dogs like me. My human enjoyed a cappuccino, and I couldn't resist sniffing the pastries. It's the perfect place for a furry friend to chill and people-watch!",
      rating: 4,
      date: '2023-10-26',
    },
    {
      id: 6,
      location: 'The Green Garden Grill',
      title: 'Vegetarian Delights at The Green Garden Grill',
      text: 'I had a woofderful time at The Green Garden Grill. Their pet-friendly courtyard is a haven for pups like me. I tried their veggie burger, and it was tail-waggingly good! The lush surroundings and fresh air make it a perfect spot for us four-legged friends.',
      rating: 5,
      date: '2023-10-25',
    },
    {
      id: 7,
      location: 'Gourmet Fusion Kitchen',
      title: 'A Fusion Adventure at Gourmet Fusion Kitchen',
      text: 'Gourmet Fusion Kitchen was a taste explosion for my senses. The dog-friendly garden made it even better. I got to taste a bit of sushi, and it was pawsitively outstanding! Dining here with my human was an adventure for both of us.',
      rating: 4,
      date: '2023-10-24',
    },
    {
      id: 8,
      location: 'Sunset Beach Grill',
      title: 'Sunset Dinner at Sunset Beach Grill',
      text: "Sunset Beach Grill is the ultimate spot for a dog like me. The beachfront seating is pawfect, and I couldn't stop gazing at the waves. I tried a bit of grilled fish, and it was a real treat! Sunset dinners with my human don't get any better than this.",
      rating: 5,
      date: '2023-10-23',
    },
    {
      id: 9,
      location: 'Café Serenity',
      title: 'A Peaceful Breakfast at Café Serenity',
      text: "Café Serenity is a place where I found my zen. Their dog-friendly garden is pawradise, and the pancakes were out of this world. I couldn't resist those fluffy clouds of deliciousness. The perfect spot to start the day with my human!",
      rating: 4,
      date: '2023-10-22',
    },
    {
      id: 10,
      location: 'Farmhouse Table',
      title: 'Farm-to-Table Dining at Farmhouse Table',
      text: 'Farmhouse Table is a farm-fresh delight for dogs like me. The pet-friendly patio is a great place to chill. I had a taste of their farm-fresh dishes, and it was woofderful. The farm-to-table concept is truly impressive. Dining here with my human is always a treat!',
      rating: 5,
      date: '2023-10-21',
    },
    {
      id: 11,
      location: "Pickle's Coffee Haven",
      title: `Morning Brew at Pickle's Coffee Haven`,
      text: "Pickle's Coffee Haven is my go-to spot for morning lattes. The dog-friendly terrace is a perfect place to start the day with my human. They make the best lattes, and the aroma is just irresistible. A place for a best friend to enjoy a morning brew!",
      rating: 4,
      date: '2023-10-20',
    },
    {
      id: 12,
      location: 'Mediterranean Delights',
      title: 'A Mediterranean Feast at Mediterranean Delights',
      text: 'I had a Mediterranean feast at this restaurant. The dog-friendly courtyard was relaxing, and I got to taste the heavenly hummus. The scents and flavors made it a tail-waggingly good experience. Dining here with my human was a delight!',
      rating: 5,
      date: '2023-10-19',
    },
    {
      id: 13,
      location: 'Rooftop Dining at Vista',
      title: 'City Views at Vista',
      text: 'I had dinner with a view at Vista. The dog-friendly rooftop terrace had the city lights that had me mesmerized. My human enjoyed the food, and I enjoyed the breeze. A place to savor with your best furry friend!',
      rating: 4,
      date: '2023-10-18',
    },
    {
      id: 14,
      location: 'Taste of Tuscany',
      title: 'Taste of Italy at Taste of Tuscany',
      text: 'I had a taste of Italy at Taste of Tuscany. The dog-friendly patio was charming, and the pasta was a mouthwatering delight. A place for a dog like me to enjoy a taste of Italy with my human!',
      rating: 5,
      date: '2023-10-17',
    },
  ])
}
